# -*- coding: utf-8 -*-
"""ML_Pract-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsexIHzBitUVgLOS8QX9ABpuZ7ZCTZdD
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize the data
x_train = x_train / 255.0
x_test = x_test / 255.0

# Flatten the images
x_train = x_train.reshape(-1, 28*28)
x_test = x_test.reshape(-1, 28*28)

# Define the model
model = keras.Sequential([
    layers.Input(shape=(784,)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate on test data
loss, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\nModel Accuracy on Test Data: {acc:.2f}")

# Plot training accuracy
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# Save the model
model.save("mnist_digit_model.h5")

# Basic git setup
!git --version
!git config --global user.name "arpita1003991"
!git config --global user.email "arpitadani28@gmail.com"

from getpass import getpass

GITHUB_USERNAME = "arpita1003991"
REPO_NAME = "Practical10_TensorFlow_Keras"
TOKEN = getpass("Paste your GitHub Personal Access Token (input hidden): ")

REPO_URL = f"https://{GITHUB_USERNAME}:{TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"
print("Repository URL prepared.")

!git clone {REPO_URL}

!cp -r Practical10_TensorFlow_Keras/* {REPO_NAME}/

!cp mnist_digit_model.h5 {REPO_NAME}/ || true

!ls -la {REPO_NAME}

# Commit & push safely
!cd {REPO_NAME} && \
git add . && \
git commit -m "Initial commit: add notebook, model, README, and .gitignore" && \
git branch -M main && \
git push {REPO_URL} main

!cd Practical10_TensorFlow_Keras && git push {REPO_URL} main